import type { Locale } from "./config";

export type PrivacySection = { heading: string; paragraphs: readonly string[] };
export type PrivacyDocument = { title: string; version: string; sections: readonly PrivacySection[] };

const fr: PrivacyDocument = {
  title: "POLITIQUE DE CONFIDENTIALITÉ — KHAOS THEORY",
  version: "Version : septembre 2026",
  sections: [
    { heading: "1. Responsable du traitement", paragraphs: ["Le responsable du traitement des données personnelles collectées dans le cadre du site khaostheoryparis.com est :\nEI – Vincent GÉRARD, exerçant sous le nom commercial Khaos Theory\n231 Rue Saint-Honoré\n75001 Paris\nFrance\n\nE-mail : contact@khaostheoryparis.com"] },
    { heading: "2. Données susceptibles d’être traitées", paragraphs: ["Dans le cadre de la navigation, de la gestion du panier, d’une commande, d’un paiement, d’une livraison, d’une facturation ou d’un remboursement, Khaos Theory peut traiter notamment :\n\nles nom et prénom du client, son adresse électronique, son numéro de téléphone lorsqu’il est fourni, ses adresses de livraison et de facturation, le pays, la ville et le code postal, les produits commandés, tailles, quantités, prix, frais de livraison, montants payés ou remboursés, ainsi que les références techniques nécessaires au suivi de la commande et du paiement.", "Le panier peut être enregistré localement dans le navigateur de l’utilisateur afin de permettre son fonctionnement."] },
    { heading: "3. Données de paiement", paragraphs: ["Les paiements sont traités par Stripe.", "Les informations de carte bancaire sont saisies directement dans les composants de paiement Stripe et ne sont pas enregistrées dans les bases de données de Khaos Theory.", "Khaos Theory conserve uniquement les références techniques nécessaires au rapprochement du paiement et de la commande, telles que les identifiants Stripe associés à la transaction."] },
    { heading: "4. Finalités et bases légales", paragraphs: ["Les données personnelles sont traitées notamment afin de :\n- gérer le panier, les commandes, paiements, livraisons, retours et remboursements ;\n- établir et conserver les factures et avoirs ;\n- assurer le suivi et le service client ;\n- prévenir et traiter les incidents techniques ou les contestations ;\n- respecter les obligations comptables, fiscales et légales de Khaos Theory.", "Les traitements nécessaires à la commande et à son exécution reposent principalement sur l’exécution du contrat. Les traitements imposés par la législation reposent sur une obligation légale. Certains traitements nécessaires à la sécurité, à la prévention des incidents et au bon fonctionnement du service peuvent reposer sur l’intérêt légitime de Khaos Theory."] },
    { heading: "5. Destinataires et prestataires", paragraphs: ["Les données ne sont accessibles qu’aux personnes et prestataires qui en ont besoin pour les finalités correspondantes.", "Khaos Theory utilise notamment :\n\nStripe, pour le traitement des paiements et les opérations liées aux transactions ;\n\nPennylane, pour la gestion des clients, factures, avoirs et, dans l’état actuel du service, l’envoi de certains documents transactionnels par e-mail ;\n\nCloudflare, pour l’hébergement et l’exécution du site et de ses API, le stockage de certaines données de commande, les files de traitement, les journaux techniques et la protection de l’espace d’administration ;\n\nGoogle Fonts, actuellement utilisé pour charger la police Alumni Sans affichée sur le site.", "Les données peuvent également être transmises à d’autres destinataires lorsque cela est nécessaire à l’exécution d’une obligation légale ou à la défense des droits de Khaos Theory."] },
    { heading: "6. Données de commande conservées par Khaos Theory", paragraphs: ["Khaos Theory conserve dans son système notamment les informations nécessaires au suivi des commandes et remboursements : identité et e-mail du client, contenu de la commande, tailles, quantités, prix, montants, statut, frais de livraison et références techniques Stripe et Pennylane.", "Les adresses complètes de livraison et de facturation ne sont actuellement pas conservées dans la base de données applicative de Khaos Theory. Elles peuvent néanmoins être traitées et conservées par les prestataires auxquels elles sont nécessaires, notamment Stripe et Pennylane."] },
    { heading: "7. Durées de conservation", paragraphs: ["Les données utilisées activement pour gérer une commande sont conservées pendant la durée nécessaire à son traitement et au suivi de la relation correspondante.", "Les données nécessaires à la facturation et au respect des obligations comptables peuvent ensuite être conservées pendant 10 ans, conformément aux obligations applicables.", "Les données techniques et journaux sont conservés pendant une durée limitée déterminée en fonction de leur finalité, des impératifs de sécurité et des paramètres des services techniques utilisés.", "Khaos Theory n’a pas pour objectif de conserver indéfiniment des données personnelles ne présentant plus d’utilité légale, contractuelle ou opérationnelle."] },
    { heading: "8. Stockage dans le navigateur et traceurs", paragraphs: ["Le site utilise actuellement le stockage local du navigateur (localStorage) afin de conserver le contenu du panier sous la clé nécessaire au fonctionnement du panier.", "Aucun outil de publicité comportementale ou de mesure d’audience tel que Google Analytics, Meta Pixel, TikTok Pixel ou Hotjar n’est actuellement intégré au site.", "Stripe.js et Stripe Elements sont utilisés lorsque l’utilisateur accède au processus de paiement.", "La police Alumni Sans est actuellement chargée au moyen du service Google Fonts, ce qui implique une connexion du navigateur à l’infrastructure de Google lors du chargement de cette ressource.", "Cette section devra être mise à jour si de nouveaux outils de mesure d’audience, publicité ou autres traceurs sont ajoutés ultérieurement."] },
    { heading: "9. Transferts internationaux", paragraphs: ["Certains prestataires utilisés par Khaos Theory sont des groupes internationaux et peuvent traiter ou permettre l’accès à certaines données en dehors de l’Espace économique européen.", "Lorsque cela est nécessaire, ces transferts doivent être encadrés par les mécanismes reconnus par la réglementation applicable, notamment une décision d’adéquation, le Data Privacy Framework lorsqu’il est applicable ou des clauses contractuelles types approuvées par la Commission européenne."] },
    { heading: "10. Sécurité", paragraphs: ["Khaos Theory met en œuvre des mesures techniques et organisationnelles destinées à protéger les données personnelles contre l’accès non autorisé, la perte, l’altération ou la divulgation.", "Les données de carte bancaire ne sont pas stockées dans les bases de données applicatives Khaos Theory et sont prises en charge par l’infrastructure de paiement Stripe."] },
    { heading: "11. Droits des personnes", paragraphs: ["Conformément à la réglementation applicable en matière de protection des données personnelles, toute personne concernée peut, selon les conditions prévues par la réglementation, demander l’accès à ses données, leur rectification, leur effacement, la limitation de leur traitement ou exercer son droit d’opposition.", "Lorsque le traitement repose sur le consentement, celui-ci peut être retiré à tout moment sans remettre en cause la licéité des traitements réalisés auparavant.", "Lorsque les conditions légales sont réunies, un droit à la portabilité peut également être exercé.", "Toute demande peut être adressée à :\ncontact@khaostheoryparis.com", "Khaos Theory peut demander les informations raisonnablement nécessaires pour vérifier l’identité du demandeur lorsqu’un doute existe."] },
    { heading: "12. Réclamation auprès de la CNIL", paragraphs: ["Toute personne estimant que ses droits relatifs à ses données personnelles ne sont pas respectés peut également introduire une réclamation auprès de la Commission nationale de l’informatique et des libertés (CNIL)."] },
    { heading: "13. Contact", paragraphs: ["Pour toute question relative à cette politique ou au traitement des données personnelles :\n\ncontact@khaostheoryparis.com"] },
    { heading: "14. Modification de la politique", paragraphs: ["Khaos Theory peut modifier la présente politique afin de tenir compte de l’évolution de ses services, de ses prestataires ou de la réglementation.", "La version publiée sur le site est la version applicable au moment de sa consultation."] },
  ],
};

const en: PrivacyDocument = {
  title: "PRIVACY POLICY — KHAOS THEORY",
  version: "Version: September 2026",
  sections: [
    { heading: "1. Data controller", paragraphs: ["The data controller for personal data collected through khaostheoryparis.com is:\nEI – Vincent GÉRARD, trading as Khaos Theory\n231 Rue Saint-Honoré\n75001 Paris\nFrance\n\nEmail: contact@khaostheoryparis.com"] },
    { heading: "2. Data that may be processed", paragraphs: ["In connection with browsing, cart management, an order, payment, delivery, invoicing or a refund, Khaos Theory may process in particular:\n\nThe customer’s first and last name, email address, telephone number when provided, delivery and billing addresses, country, city and postal code, ordered products, sizes, quantities, prices, delivery charges, amounts paid or refunded, and technical references needed to track the order and payment.", "The cart may be stored locally in the user’s browser so that the cart can operate."] },
    { heading: "3. Payment data", paragraphs: ["Payments are processed by Stripe.", "Card details are entered directly into Stripe payment components and are not stored in Khaos Theory databases.", "Khaos Theory retains only the technical references needed to reconcile the payment and order, such as Stripe identifiers associated with the transaction."] },
    { heading: "4. Purposes and legal bases", paragraphs: ["Personal data is processed in particular to:\n- manage the cart, orders, payments, deliveries, returns and refunds;\n- issue and retain invoices and credit notes;\n- provide order follow-up and customer service;\n- prevent and handle technical incidents or disputes;\n- comply with Khaos Theory’s accounting, tax and legal obligations.", "Processing necessary for the order and its performance is primarily based on performance of the contract. Processing required by legislation is based on a legal obligation. Certain processing necessary for security, incident prevention and proper operation of the service may be based on Khaos Theory’s legitimate interest."] },
    { heading: "5. Recipients and service providers", paragraphs: ["Data is accessible only to people and service providers who need it for the relevant purposes.", "Khaos Theory uses in particular:\n\nStripe, for payment processing and transaction-related operations;\n\nPennylane, for managing customers, invoices and credit notes and, under the current service configuration, sending certain transactional documents by email;\n\nCloudflare, for hosting and running the site and its APIs, storing certain order data, processing queues, technical logs and protecting the administration area;\n\nGoogle Fonts, currently used to load the Alumni Sans font displayed on the site.", "Data may also be disclosed to other recipients where necessary to comply with a legal obligation or defend Khaos Theory’s rights."] },
    { heading: "6. Order data retained by Khaos Theory", paragraphs: ["Khaos Theory retains in its system the information needed to track orders and refunds, including customer identity and email, order contents, sizes, quantities, prices, amounts, status, delivery charges and Stripe and Pennylane technical references.", "Complete delivery and billing addresses are not currently retained in Khaos Theory’s application database. They may nevertheless be processed and retained by providers that need them, in particular Stripe and Pennylane."] },
    { heading: "7. Retention periods", paragraphs: ["Data actively used to manage an order is retained for the time necessary to process it and follow the related relationship.", "Data needed for invoicing and compliance with accounting obligations may then be retained for 10 years, in accordance with applicable obligations.", "Technical data and logs are retained for a limited period determined by their purpose, security requirements and the settings of the technical services used.", "Khaos Theory does not intend to retain personal data indefinitely when it no longer has legal, contractual or operational utility."] },
    { heading: "8. Browser storage and trackers", paragraphs: ["The site currently uses local browser storage (localStorage) to retain cart contents under the key needed for cart operation.", "No behavioural advertising or audience measurement tool such as Google Analytics, Meta Pixel, TikTok Pixel or Hotjar is currently integrated into the site.", "Stripe.js and Stripe Elements are used when the user enters the payment process.", "The Alumni Sans font is currently loaded through Google Fonts, which involves the browser connecting to Google infrastructure when the resource loads.", "This section must be updated if new audience measurement, advertising or other tracking tools are added later."] },
    { heading: "9. International transfers", paragraphs: ["Some providers used by Khaos Theory are international groups and may process or allow access to certain data outside the European Economic Area (EEA).", "Where necessary, these transfers must be governed by mechanisms recognised by applicable law, including an adequacy decision, the Data Privacy Framework where applicable, or Standard Contractual Clauses approved by the European Commission."] },
    { heading: "10. Security", paragraphs: ["Khaos Theory implements technical and organisational measures intended to protect personal data against unauthorised access, loss, alteration or disclosure.", "Card data is not stored in Khaos Theory application databases and is handled by Stripe’s payment infrastructure."] },
    { heading: "11. Data subject rights", paragraphs: ["Under applicable data protection law, each data subject may, subject to the conditions provided by law, request access to their data, rectification, erasure, restriction of processing or exercise the right to object.", "Where processing is based on consent, consent may be withdrawn at any time without affecting the lawfulness of processing carried out before withdrawal.", "Where the legal conditions are met, the right to data portability may also be exercised.", "Requests may be sent to:\ncontact@khaostheoryparis.com", "Khaos Theory may request information reasonably necessary to verify the requester’s identity where there is doubt."] },
    { heading: "12. Complaint to the CNIL", paragraphs: ["Any person who considers that their rights relating to personal data have not been respected may also lodge a complaint with the Commission nationale de l’informatique et des libertés (CNIL), the French data protection authority."] },
    { heading: "13. Contact", paragraphs: ["For any question about this policy or the processing of personal data:\n\ncontact@khaostheoryparis.com"] },
    { heading: "14. Changes to this policy", paragraphs: ["Khaos Theory may amend this policy to reflect changes to its services, providers or applicable regulations.", "The version published on the site is the version applicable when it is consulted."] },
  ],
};

export const privacyDocuments: Record<Locale, PrivacyDocument> = { fr, en };
