import type { Locale } from "./config";

export type PrivacySection = { heading: string; paragraphs: readonly string[] };
export type PrivacyDocument = { title: string; version: string; sections: readonly PrivacySection[] };

const fr: PrivacyDocument = {
  title: "POLITIQUE DE CONFIDENTIALITÉ — KHAOS THEORY",
  version: "Version : septembre 2026",
  sections: [
    { heading: "1. Responsable du traitement", paragraphs: ["Le responsable du traitement des données personnelles collectées dans le cadre du site Khaos Theory est :\nEI – Vincent GÉRARD\nNom commercial : Khaos Theory\n231 Rue Saint-Honoré\n75001 Paris\nFrance\n\nSIREN : 928 374 297\nSIRET : 928 374 297 00028\n\nE-mail : contact@khaostheoryparis.com"] },
    { heading: "2. Objet de la présente politique", paragraphs: ["La présente politique explique quelles données personnelles peuvent être traitées dans le cadre de l’utilisation du site Khaos Theory, de la passation et de l’exécution des commandes, des paiements, de la facturation, des remboursements et de la relation avec les clients.", "Khaos Theory s’efforce de limiter la collecte et le traitement des données aux informations nécessaires aux finalités décrites ci-dessous."] },
    { heading: "3. Données traitées", paragraphs: ["Selon l’utilisation du site et les opérations effectuées, les catégories de données suivantes peuvent notamment être traitées :\n\n- identité : nom et prénom ;\n- coordonnées : adresse e-mail et, lorsqu’il est fourni ou nécessaire, numéro de téléphone ;\n- adresse de livraison et adresse de facturation ;\n- pays, ville et code postal ;\n- informations relatives à la commande : produits, références, tailles, quantités, prix, frais de livraison et montant total ;\n- informations relatives au paiement et au remboursement, telles que les identifiants techniques de transaction, de session de paiement ou de remboursement ;\n- informations nécessaires à la facturation et à l’établissement éventuel d’avoirs ;\n- informations techniques nécessaires au fonctionnement, à la sécurité et à l’administration du service.", "Khaos Theory ne reçoit ni ne stocke directement les numéros complets de carte bancaire saisis dans l’interface de paiement Stripe."] },
    { heading: "4. Finalités et bases légales des traitements", paragraphs: ["Les données peuvent être traitées afin de :\n\n- permettre la création, le paiement et l’exécution d’une commande ;\n- fabriquer et expédier les produits commandés ;\n- gérer les paiements, remboursements, retours et réclamations ;\n- établir et gérer les factures et avoirs ;\n- assurer la comptabilité et respecter les obligations légales, fiscales et réglementaires applicables ;\n- communiquer avec le client au sujet de sa commande ;\n- assurer le fonctionnement, la sécurité, la prévention des abus et l’administration technique du site ;\n- permettre l’exercice et la défense des droits de Khaos Theory lorsque cela est nécessaire.", "Selon la finalité concernée, le traitement repose notamment sur l’exécution du contrat ou de mesures précontractuelles, le respect d’une obligation légale ou, lorsque cela est applicable, l’intérêt légitime de Khaos Theory à assurer la sécurité, le fonctionnement du service et la défense de ses droits."] },
    { heading: "5. Caractère nécessaire des données", paragraphs: ["Certaines informations sont nécessaires pour permettre la conclusion et l’exécution d’une commande, notamment l’identité du client, son adresse e-mail, les informations de livraison et les informations nécessaires au paiement.", "L’absence de certaines de ces informations peut empêcher Khaos Theory de traiter ou d’exécuter la commande.", "Les informations facultatives sont identifiées comme telles lorsqu’elles sont proposées."] },
    { heading: "6. Paiements — Stripe", paragraphs: ["Les paiements sont traités à l’aide des services de Stripe.", "Dans le cadre d’un paiement, certaines données nécessaires à la transaction sont transmises directement à Stripe. Khaos Theory peut recevoir les informations nécessaires au suivi de la transaction, notamment des identifiants de session de paiement, de PaymentIntent, des montants, la devise, le statut du paiement et les références nécessaires au rapprochement avec la commande.", "Les données complètes de carte bancaire ne sont pas reçues ni stockées directement par Khaos Theory.", "Stripe traite les données qui lui sont transmises conformément à ses propres obligations et conditions applicables."] },
    { heading: "7. Facturation et comptabilité — Pennylane", paragraphs: ["Khaos Theory utilise Pennylane pour certaines opérations de facturation et de comptabilité.", "Les informations nécessaires à ces opérations peuvent notamment comprendre le nom et le prénom du client, son adresse e-mail, son adresse de facturation, son numéro de téléphone lorsqu’il est disponible, les informations relatives aux produits commandés, les prix, les frais de livraison, la devise ainsi que les références nécessaires au rapprochement avec les transactions correspondantes.", "Ces données peuvent également être utilisées pour établir des factures et des avoirs."] },
    { heading: "8. Infrastructure — Cloudflare", paragraphs: ["Khaos Theory utilise les services de Cloudflare pour l’hébergement et l’exécution de certaines fonctions du site, ainsi que pour des services techniques comprenant notamment le stockage de certaines données, le traitement de files d’événements et la protection des interfaces administratives.", "Dans ce cadre, des données techniques et certaines informations nécessaires au traitement des commandes peuvent transiter ou être stockées au sein de cette infrastructure.", "Des journaux techniques peuvent également être générés afin d’assurer le fonctionnement, la sécurité et le diagnostic du service."] },
    { heading: "9. Panier et stockage local", paragraphs: ["Le panier du site est conservé localement dans le navigateur de l’utilisateur à l’aide de la technologie localStorage.", "Ce stockage peut notamment contenir les produits sélectionnés, leur référence, leur nom, leur prix, leur taille et leur quantité.", "Ces informations restent dans le stockage local du navigateur jusqu’à leur suppression par le fonctionnement du site, par l’utilisateur ou par les mécanismes du navigateur.", "Les modalités relatives aux cookies et technologies similaires sont détaillées dans la Politique relative aux cookies de Khaos Theory :\n/fr/cookies"] },
    { heading: "10. Contact avec Khaos Theory", paragraphs: ["La page Contact ne comporte actuellement aucun formulaire collectant directement des données sur le site.", "Lorsqu’une personne contacte Khaos Theory par e-mail, les informations qu’elle communique volontairement sont utilisées afin de répondre à sa demande et d’assurer, lorsque cela est nécessaire, le suivi de la relation ou de la commande concernée."] },
    { heading: "11. Données de paiement et de remboursement", paragraphs: ["Khaos Theory conserve ou utilise certaines références techniques nécessaires au suivi des paiements et remboursements, telles que les identifiants de Checkout Session, PaymentIntent ou Refund fournis par Stripe.", "Ces références permettent notamment de rapprocher les opérations de paiement, les commandes, les remboursements, les factures et les avoirs.", "Elles ne correspondent pas au numéro complet de la carte bancaire du client."] },
    { heading: "12. Destinataires et prestataires", paragraphs: ["Dans la limite nécessaire à leurs missions respectives, les données peuvent être traitées par Khaos Theory ainsi que par les prestataires utilisés pour fournir les services nécessaires au fonctionnement du site et à l’exécution des commandes.", "Les principaux prestataires actuellement utilisés comprennent notamment :\n\n- Stripe pour le traitement des paiements et remboursements ;\n- Pennylane pour la facturation, les avoirs et certaines opérations comptables ;\n- Cloudflare pour l’infrastructure technique, l’exécution du site, certaines fonctions de stockage et de sécurité.", "Khaos Theory ne vend pas les données personnelles de ses clients."] },
    { heading: "13. Transferts internationaux de données", paragraphs: ["Certains prestataires techniques utilisés par Khaos Theory peuvent traiter des données depuis ou vers des pays situés en dehors de l’Espace économique européen.", "Lorsque la réglementation l’exige, ces traitements doivent être encadrés par un mécanisme reconnu par la réglementation applicable en matière de protection des données, notamment une décision d’adéquation ou des garanties appropriées.", "Les personnes concernées peuvent contacter Khaos Theory pour obtenir des informations complémentaires concernant les traitements qui les concernent."] },
    { heading: "14. Durées de conservation", paragraphs: ["Les données personnelles ne sont conservées que pendant la durée nécessaire aux finalités pour lesquelles elles sont traitées, sous réserve des durées imposées ou autorisées par les dispositions légales et réglementaires applicables.", "Les données nécessaires à la gestion courante d’une commande sont conservées pendant la durée nécessaire à son traitement, à son exécution et au suivi de la relation avec le client.", "Les documents et données devant être conservés afin de satisfaire aux obligations comptables et fiscales peuvent être archivés pendant la durée légalement requise, notamment pendant dix ans pour les documents comptables concernés.", "Certaines données peuvent également être conservées pendant la durée nécessaire à la constatation, à l’exercice ou à la défense de droits en justice lorsqu’une telle conservation est justifiée.", "Les données traitées par des prestataires tels que Stripe, Pennylane ou Cloudflare peuvent être soumises à leurs propres durées de conservation, conformément à leurs obligations et politiques respectives."] },
    { heading: "15. Sécurité", paragraphs: ["Khaos Theory met en œuvre des mesures techniques et organisationnelles destinées à protéger les données personnelles contre l’accès non autorisé, la perte, l’altération, la divulgation ou l’utilisation illicite.", "L’accès aux interfaces administratives est notamment soumis à des mécanismes de contrôle d’accès.", "Aucun système informatique ne pouvant garantir une sécurité absolue, les mesures mises en œuvre sont adaptées et réévaluées en fonction des risques et de l’évolution du service."] },
    { heading: "16. Droits des personnes", paragraphs: ["Conformément à la réglementation applicable en matière de protection des données personnelles, les personnes concernées peuvent, selon les conditions prévues par celle-ci, disposer notamment des droits suivants :\n\n- droit d’accès à leurs données personnelles ;\n- droit de rectification des données inexactes ou incomplètes ;\n- droit à l’effacement dans les cas prévus par la réglementation ;\n- droit à la limitation du traitement ;\n- droit d’opposition lorsque le traitement concerné le permet ;\n- droit à la portabilité lorsque les conditions légales sont réunies.", "L’exercice de certains droits peut être limité lorsqu’un traitement ou une conservation est nécessaire au respect d’une obligation légale, à l’exécution d’un contrat ou à la constatation, l’exercice ou la défense de droits en justice."] },
    { heading: "17. Exercice des droits", paragraphs: ["Toute demande relative aux données personnelles peut être adressée à :\n\ncontact@khaostheoryparis.com", "Khaos Theory pourra demander les informations raisonnablement nécessaires pour vérifier l’identité du demandeur lorsque cette vérification est nécessaire afin d’éviter la communication de données à une personne non autorisée."] },
    { heading: "18. Réclamation auprès de la CNIL", paragraphs: ["Toute personne concernée dispose également du droit d’introduire une réclamation auprès de l’autorité de contrôle compétente.", "En France, l’autorité compétente est la Commission nationale de l’informatique et des libertés (CNIL).\nhttps://www.cnil.fr/"] },
    { heading: "19. Prospection commerciale et analyse d’audience", paragraphs: ["À la date de la présente version, Khaos Theory n’utilise pas le site pour mettre en œuvre des pixels publicitaires ou des outils d’analyse d’audience tels que Google Analytics, Meta Pixel, TikTok Pixel ou Hotjar.", "Khaos Theory n’utilise pas les données de commande afin de mettre en œuvre une prise de décision automatisée produisant des effets juridiques ou similaires à l’égard du client.", "Si ces pratiques évoluent, la présente politique et, lorsque cela est nécessaire, les mécanismes de consentement du site seront adaptés avant leur mise en œuvre."] },
    { heading: "20. Modification de la politique", paragraphs: ["Khaos Theory peut modifier la présente Politique de confidentialité afin de tenir compte notamment de l’évolution du site, de ses services, de ses prestataires ou des obligations légales applicables.", "La version publiée sur le site est la version actuellement applicable.", "Dernière mise à jour : septembre 2026."] },
  ],
};

const en: PrivacyDocument = {
  title: "PRIVACY POLICY — KHAOS THEORY",
  version: "Version: September 2026",
  sections: [
    { heading: "1. Data controller", paragraphs: ["The data controller for personal data collected through the Khaos Theory website is:\nEI – Vincent GÉRARD\nTrading name: Khaos Theory\n231 Rue Saint-Honoré\n75001 Paris\nFrance\n\nSIREN: 928 374 297\nSIRET: 928 374 297 00028\n\nEmail: contact@khaostheoryparis.com"] },
    { heading: "2. Purpose of this policy", paragraphs: ["This policy explains which personal data may be processed when using the Khaos Theory website, placing and performing orders, making payments, invoicing, processing refunds and managing customer relations.", "Khaos Theory seeks to limit collection and processing to information necessary for the purposes described below."] },
    { heading: "3. Data processed", paragraphs: ["Depending on how the site is used and which operations are performed, the following categories of data may be processed in particular:\n\n- identity: first and last name;\n- contact details: email address and, when provided or necessary, telephone number;\n- delivery and billing addresses;\n- country, city and postal code;\n- order information: products, references, sizes, quantities, prices, delivery charges and total amount;\n- payment and refund information, such as technical transaction, payment-session or refund identifiers;\n- information needed for invoicing and any credit notes;\n- technical information needed to operate, secure and administer the service.", "Khaos Theory does not receive or directly store the full card numbers entered in the Stripe payment interface."] },
    { heading: "4. Purposes and legal bases", paragraphs: ["Data may be processed in order to:\n\n- enable the creation, payment and performance of an order;\n- manufacture and dispatch ordered products;\n- manage payments, refunds, returns and claims;\n- issue and manage invoices and credit notes;\n- manage accounting and comply with applicable legal, tax and regulatory obligations;\n- communicate with the customer about the order;\n- operate, secure and technically administer the site and prevent abuse;\n- enable the exercise and defence of Khaos Theory’s rights where necessary.", "Depending on the purpose, processing is based in particular on performance of the contract or pre-contractual measures, compliance with a legal obligation or, where applicable, Khaos Theory’s legitimate interest in securing and operating the service and defending its rights."] },
    { heading: "5. Necessity of data", paragraphs: ["Certain information is necessary to conclude and perform an order, including the customer’s identity, email address, delivery information and information needed for payment.", "The absence of some of this information may prevent Khaos Theory from processing or performing the order.", "Optional information is identified as such when offered."] },
    { heading: "6. Payments — Stripe", paragraphs: ["Payments are processed using Stripe services.", "For a payment, certain data necessary for the transaction is transmitted directly to Stripe. Khaos Theory may receive information needed to track the transaction, including payment-session and PaymentIntent identifiers, amounts, currency, payment status and references needed to reconcile the order.", "Full card data is not received or directly stored by Khaos Theory.", "Stripe processes the data transmitted to it in accordance with its own applicable obligations and terms."] },
    { heading: "7. Invoicing and accounting — Pennylane", paragraphs: ["Khaos Theory uses Pennylane for certain invoicing and accounting operations.", "Information needed for these operations may include the customer’s first and last name, email address, billing address, telephone number where available, ordered-product information, prices, delivery charges, currency and references needed to reconcile the corresponding transactions.", "This data may also be used to issue invoices and credit notes."] },
    { heading: "8. Infrastructure — Cloudflare", paragraphs: ["Khaos Theory uses Cloudflare services to host and run certain site functions, as well as technical services including storage of certain data, event-queue processing and protection of administrative interfaces.", "In this context, technical data and certain information needed to process orders may transit or be stored within this infrastructure.", "Technical logs may also be generated to operate, secure and diagnose the service."] },
    { heading: "9. Cart and local storage", paragraphs: ["The site cart is stored locally in the user’s browser using localStorage.", "This storage may contain selected products, their reference, name, price, size and quantity.", "This information remains in the browser’s local storage until removed by the site, the user or browser mechanisms.", "The arrangements for cookies and similar technologies are described in Khaos Theory’s Cookies Policy:\n/en/cookies"] },
    { heading: "10. Contacting Khaos Theory", paragraphs: ["The Contact page currently has no form that directly collects data on the site.", "When someone contacts Khaos Theory by email, the information they voluntarily provide is used to answer the request and, where necessary, follow up the related relationship or order."] },
    { heading: "11. Payment and refund data", paragraphs: ["Khaos Theory retains or uses technical references needed to track payments and refunds, such as Checkout Session, PaymentIntent or Refund identifiers provided by Stripe.", "These references help reconcile payment operations, orders, refunds, invoices and credit notes.", "They are not the customer’s full card number."] },
    { heading: "12. Recipients and providers", paragraphs: ["To the extent necessary for their respective tasks, data may be processed by Khaos Theory and by providers used to deliver the services necessary to operate the site and perform orders.", "The main providers currently used include:\n\n- Stripe for payment and refund processing;\n- Pennylane for invoicing, credit notes and certain accounting operations;\n- Cloudflare for technical infrastructure, site execution and certain storage and security functions.", "Khaos Theory does not sell its customers’ personal data."] },
    { heading: "13. International data transfers", paragraphs: ["Some technical providers used by Khaos Theory may process data from or allow access to data in countries outside the European Economic Area (EEA).", "Where required by law, these operations must be governed by a mechanism recognised under applicable data-protection law, including an adequacy decision or appropriate safeguards.", "Data subjects may contact Khaos Theory for further information about processing concerning them."] },
    { heading: "14. Retention periods", paragraphs: ["Personal data is retained only for as long as necessary for the purposes for which it is processed, subject to periods required or permitted by applicable laws and regulations.", "Data needed for day-to-day order management is retained for the time necessary to process and perform the order and follow the customer relationship.", "Documents and data that must be retained for accounting and tax obligations may be archived for the legally required period, including ten years for the relevant accounting documents.", "Certain data may also be retained for as long as necessary to establish, exercise or defend legal claims where justified.", "Data processed by providers such as Stripe, Pennylane or Cloudflare may be subject to their own retention periods under their respective obligations and policies."] },
    { heading: "15. Security", paragraphs: ["Khaos Theory implements technical and organisational measures intended to protect personal data against unauthorised access, loss, alteration, disclosure or unlawful use.", "Access to administrative interfaces is subject to access-control mechanisms.", "As no information system can guarantee absolute security, measures are adapted and reassessed according to risks and service changes."] },
    { heading: "16. Data subject rights", paragraphs: ["Under applicable personal-data protection law, data subjects may, subject to the conditions provided by law, have in particular the following rights:\n\n- right of access to their personal data;\n- right to rectification of inaccurate or incomplete data;\n- right to erasure where provided by law;\n- right to restriction of processing;\n- right to object where the relevant processing allows it;\n- right to data portability where legal conditions are met.", "The exercise of certain rights may be limited where processing or retention is necessary to comply with a legal obligation, perform a contract or establish, exercise or defend legal claims."] },
    { heading: "17. Exercising rights", paragraphs: ["Requests concerning personal data may be sent to:\n\ncontact@khaostheoryparis.com", "Khaos Theory may request information reasonably necessary to verify the requester’s identity where this is necessary to avoid disclosing data to an unauthorised person."] },
    { heading: "18. Complaint to the CNIL", paragraphs: ["Data subjects also have the right to lodge a complaint with the competent supervisory authority.", "In France, the competent authority is the Commission nationale de l’informatique et des libertés (CNIL), the French data-protection authority.\nhttps://www.cnil.fr/"] },
    { heading: "19. Commercial prospecting and audience analysis", paragraphs: ["As of this version, Khaos Theory does not use the site to deploy advertising pixels or audience-analysis tools such as Google Analytics, Meta Pixel, TikTok Pixel or Hotjar.", "Khaos Theory does not use order data to carry out automated decision-making producing legal or similarly significant effects for the customer.", "If these practices change, this policy and, where necessary, the site’s consent mechanisms will be adapted before implementation."] },
    { heading: "20. Changes to this policy", paragraphs: ["Khaos Theory may amend this Privacy Policy to reflect changes to the site, its services, providers or applicable legal obligations.", "The version published on the site is the version currently applicable.", "Last updated: September 2026."] },
  ],
};

export const privacyDocuments: Record<Locale, PrivacyDocument> = { fr, en };
