import type { Locale } from "./config";

export type TermsSection = {
  heading: string;
  paragraphs: readonly string[];
};

export type TermsDocument = {
  title: string;
  version: string;
  sections: readonly TermsSection[];
  withdrawalForm: {
    heading: string;
    paragraphs: readonly string[];
  };
};

const fr: TermsDocument = {
  title: "CONDITIONS GÉNÉRALES DE VENTE — KHAOS THEORY",
  version: "Version : septembre 2026",
  sections: [
    { heading: "1. Identité du vendeur", paragraphs: ["Les présentes Conditions Générales de Vente sont proposées par EI – Vincent GÉRARD, exerçant sous le nom commercial Khaos Theory, 231 Rue Saint-Honoré, 75001 Paris, France, SIREN 928 374 297, SIRET 928 374 297 00028.", "E-mail : contact@khaostheoryparis.com\nTéléphone : 01 84 16 47 78", "TVA non applicable, art. 293 B du CGI."] },
    { heading: "2. Champ d'application", paragraphs: ["Les présentes CGV régissent les ventes de bijoux Khaos Theory conclues à distance par l'intermédiaire du site khaostheoryparis.com avec des consommateurs. Le client reconnaît avoir pris connaissance des présentes CGV avant la validation de sa commande."] },
    { heading: "3. Produits", paragraphs: ["Les caractéristiques essentielles des produits sont présentées sur leurs fiches respectives. Les bijoux Khaos Theory sont issus d’une fabrication artisanale.", "Des variations de texture, de finition, d’aspect, de patine ou de traitement de surface peuvent exister d’une pièce à l’autre. Elles sont inhérentes au processus de fabrication artisanal et contribuent au caractère unique de chaque bijou.", "Ces variations ne constituent pas, en elles-mêmes, un défaut de conformité, sous réserve des garanties légales applicables."] },
    { heading: "4. Fabrication à la commande", paragraphs: ["Chaque pièce Khaos Theory est fabriquée à la commande. Le délai de fabrication est généralement de 4 à 6 semaines à compter de la confirmation de la commande. Ce délai n'inclut pas le délai d'acheminement après expédition.", "Les informations relatives au délai de livraison applicables à la commande sont communiquées au client avant sa validation. Les droits légaux du consommateur relatifs aux délais de livraison demeurent applicables."] },
    { heading: "5. Prix", paragraphs: ["Les prix sont indiqués en euros. Khaos Theory bénéficie de la franchise en base de TVA : « TVA non applicable, art. 293 B du CGI ».", "Les frais de livraison sont indiqués au client avant la validation de la commande et s'ajoutent au prix des produits lorsqu'ils sont applicables."] },
    { heading: "6. Commande", paragraphs: ["Avant le paiement, le client peut vérifier les produits sélectionnés, leurs tailles et quantités, les prix, les frais de livraison et le montant total de sa commande et corriger d'éventuelles erreurs.", "Le client doit également pouvoir prendre connaissance, avant de commander, des informations essentielles relatives notamment aux délais de fabrication et de livraison ainsi qu'aux éventuels droits, taxes et frais liés à une livraison internationale.", "La validation de la commande est subordonnée à l'acceptation expresse des présentes CGV."] },
    { heading: "7. Paiement", paragraphs: ["Le paiement est effectué au moyen des modes proposés lors du passage de la commande. La commande n'est considérée comme confirmée qu'après validation effective du paiement, sous réserve des contrôles éventuellement nécessaires."] },
    { heading: "8. Livraison", paragraphs: ["Les produits sont livrés à l'adresse indiquée par le client lors de sa commande. Khaos Theory sélectionne un mode d'expédition adapté à la destination, à la nature et à la valeur de l'envoi.", "Les frais et conditions de livraison applicables sont présentés avant la validation de la commande."] },
    { heading: "9. Livraisons internationales — droits et taxes", paragraphs: ["Pour les livraisons soumises à des formalités douanières, des droits de douane, taxes d'importation ou autres frais locaux peuvent être exigés par les autorités du pays de destination. Sauf indication contraire lors de la commande, ces sommes sont à la charge du destinataire et ne sont pas comprises dans les montants facturés par Khaos Theory."] },
    { heading: "10. Droit de rétractation", paragraphs: ["Lorsque le droit de rétractation est applicable, le consommateur dispose d'un délai de 14 jours à compter de la réception du bien pour exercer ce droit, sans avoir à motiver sa décision.", "Le fait qu'un bijou soit fabriqué à la commande n'exclut pas, à lui seul, le droit de rétractation.", "Le choix d'une taille standard proposée sur le site n'est pas considéré par Khaos Theory comme une personnalisation du produit.", "Le droit de rétractation peut toutefois être exclu pour un produit confectionné selon les spécifications particulières du consommateur ou clairement personnalisé, notamment lorsqu'une modification spécifique, une gravure, des dimensions particulières ou une création personnalisée ont été expressément demandées. Lorsque cette exception s'applique, le client en est informé avant la conclusion de la commande."] },
    { heading: "11. Exercice du droit de rétractation et retour", paragraphs: ["Le client peut notifier sa décision de se rétracter par une déclaration dénuée d'ambiguïté adressée à contact@khaostheoryparis.com ou utiliser le formulaire figurant en annexe.", "Après notification de sa rétractation, le produit doit être retourné dans le délai légal à :\nEI – Vincent GÉRARD / Khaos Theory\n231 Rue Saint-Honoré\n75001 Paris\nFrance", "Les frais directs de retour sont à la charge du client. Le client doit prendre les précautions raisonnablement nécessaires pour assurer un retour adapté à la nature et à la valeur du bijou."] },
    { heading: "12. Remboursement après rétractation", paragraphs: ["Lorsque les conditions légales sont réunies, Khaos Theory rembourse les sommes dues conformément aux dispositions légales applicables et en utilisant le même moyen de paiement que celui utilisé pour la transaction initiale, sauf accord exprès permettant un autre moyen sans frais pour le client.", "Le remboursement peut être différé dans les cas autorisés par la loi, notamment jusqu'à récupération du bien ou jusqu'à ce que le consommateur fournisse une preuve de son expédition."] },
    { heading: "13. Produit endommagé ou problème de livraison", paragraphs: ["Le client est invité à contacter rapidement Khaos Theory à contact@khaostheoryparis.com en cas de produit reçu endommagé, d'erreur ou de problème de livraison, afin de permettre le traitement de la situation.", "Cette démarche ne limite pas les garanties et droits légaux du consommateur."] },
    { heading: "14. Garantie légale de conformité", paragraphs: ["Le consommateur bénéficie de la garantie légale de conformité dans les conditions prévues par le Code de la consommation. Cette garantie s'applique indépendamment de toute éventuelle garantie commerciale."] },
    { heading: "15. Garantie des vices cachés", paragraphs: ["Le client bénéficie également de la garantie légale relative aux vices cachés dans les conditions prévues par le Code civil."] },
    { heading: "16. Argent, traitements de surface, textures et vieillissement du bijou", paragraphs: ["Les bijoux Khaos Theory sont notamment travaillés en argent et peuvent recevoir différents traitements de surface, effets d’oxydation, patines, textures et finitions.", "Ces traitements et textures sont susceptibles d’évoluer, de s’atténuer ou de s’altérer progressivement avec le temps et l’usage. Leur évolution peut notamment dépendre des frottements, du contact avec la peau, de l’air, de l’humidité, de produits cosmétiques ou chimiques, ainsi que des conditions de port et d’entretien du bijou.", "Cette évolution fait partie du vieillissement et de l’usure normale d’un bijou et peut contribuer au développement d’une patine propre à chaque pièce.", "Une évolution résultant de l’usage normal du bijou ne constitue donc pas, en elle-même, un défaut. Cette disposition ne prive toutefois en aucun cas le consommateur de ses garanties légales lorsqu’un défaut relevant de celles-ci est effectivement présent."] },
    { heading: "17. Taille des bijoux", paragraphs: ["Le client est responsable du choix de la taille sélectionnée parmi les tailles proposées. Une erreur de taille choisie par le client ne constitue pas, à elle seule, un défaut de conformité.", "Lorsqu'une mise à taille est techniquement possible, Khaos Theory peut éventuellement proposer cette prestation sur devis.", "Cette disposition ne limite pas l'exercice du droit de rétractation lorsque celui-ci est légalement applicable."] },
    { heading: "18. Responsabilité", paragraphs: ["Khaos Theory est responsable de l'exécution de ses obligations dans les conditions prévues par la législation applicable.", "Aucune stipulation des présentes CGV n'a pour objet ou pour effet d'exclure ou de limiter un droit impératif reconnu au consommateur."] },
    { heading: "19. Propriété intellectuelle", paragraphs: ["Les créations, photographies, textes, éléments graphiques, logos et autres contenus du site Khaos Theory sont protégés par les droits de propriété intellectuelle applicables. Toute reproduction ou exploitation non autorisée est interdite dans les limites prévues par la loi."] },
    { heading: "20. Données personnelles", paragraphs: ["Les données personnelles nécessaires au traitement des commandes et à la relation client sont traitées conformément à la politique de confidentialité de Khaos Theory, accessible sur le site."] },
    { heading: "21. Service client", paragraphs: ["Pour toute question relative à une commande, une livraison, un retour ou un remboursement, le service client Khaos Theory peut être contacté à l’adresse suivante :\ncontact@khaostheoryparis.com"] },
    { heading: "22. Médiation de la consommation", paragraphs: ["Après réclamation préalable auprès de Khaos Theory et en l'absence de résolution du litige, le consommateur peut recourir gratuitement au médiateur de la consommation dont relève Khaos Theory :\nCM2C — Centre de la Médiation de la Consommation de Conciliateurs de Justice\n49 Rue de Ponthieu\n75008 Paris\nFrance\nhttps://www.cm2c.net/"] },
    { heading: "23. Droit applicable", paragraphs: ["Les présentes CGV sont régies par le droit français, sans priver le consommateur des dispositions impératives protectrices dont il bénéficie en vertu de la législation applicable."] },
    { heading: "24. Langues", paragraphs: ["Les CGV sont proposées en français et en anglais. La version française constitue la version de référence, sans préjudice des droits impératifs dont bénéficie le consommateur."] },
    { heading: "25. Version des CGV", paragraphs: ["La version applicable est celle acceptée par le client au moment de la commande. Khaos Theory peut modifier les présentes CGV pour les commandes futures."] },
  ],
  withdrawalForm: {
    heading: "ANNEXE — FORMULAIRE TYPE DE RÉTRACTATION",
    paragraphs: ["À l'attention de :\nEI – Vincent GÉRARD / Khaos Theory\n231 Rue Saint-Honoré\n75001 Paris\nFrance\ncontact@khaostheoryparis.com", "Je vous notifie par la présente ma rétractation du contrat portant sur la vente du bien suivant :\nProduit :\nNuméro de commande :\nCommandé le / reçu le :\nNom du consommateur :\nAdresse du consommateur :\nDate :\nSignature du consommateur (uniquement en cas de formulaire papier) :"],
  },
};

const en: TermsDocument = {
  title: "TERMS AND CONDITIONS OF SALE — KHAOS THEORY",
  version: "Version: September 2026",
  sections: [
    { heading: "1. Seller identity", paragraphs: ["These Terms and Conditions of Sale are offered by EI – Vincent GÉRARD, trading as Khaos Theory, 231 Rue Saint-Honoré, 75001 Paris, France, SIREN 928 374 297, SIRET 928 374 297 00028.", "Email: contact@khaostheoryparis.com\nTelephone: +33 1 84 16 47 78", "VAT not applicable under Article 293 B of the French General Tax Code (CGI)."] },
    { heading: "2. Scope", paragraphs: ["These Terms and Conditions govern distance sales of Khaos Theory jewellery made through khaostheoryparis.com to consumers. The customer acknowledges having read these Terms before validating the order."] },
    { heading: "3. Products", paragraphs: ["The essential characteristics of the products are presented on their respective product pages. Khaos Theory jewellery is made through an artisanal process.", "Variations in texture, finish, appearance, patina or surface treatment may occur from one piece to another. They are inherent in the artisanal manufacturing process and contribute to the unique character of each piece of jewellery.", "Such variations do not, in themselves, constitute a lack of conformity, subject to applicable statutory guarantees."] },
    { heading: "4. Made-to-order production", paragraphs: ["Each Khaos Theory piece is made to order. Production generally takes 4 to 6 weeks from order confirmation. This timeframe does not include delivery time after dispatch.", "Information about the delivery timeframe applicable to the order is provided to the customer before validation. The consumer’s statutory rights concerning delivery times remain applicable."] },
    { heading: "5. Prices", paragraphs: ["Prices are stated in euros. Khaos Theory benefits from the French VAT exemption scheme: “VAT not applicable under Article 293 B of the French General Tax Code (CGI)”.", "Delivery charges are shown to the customer before the order is validated and are added to the product price where applicable."] },
    { heading: "6. Orders", paragraphs: ["Before payment, the customer may review the selected products, sizes and quantities, prices, delivery charges and total order amount, and correct any errors.", "Before ordering, the customer must also be able to review essential information, including production and delivery timeframes and any duties, taxes or charges related to international delivery.", "Validation of the order is subject to the customer’s express acceptance of these Terms and Conditions."] },
    { heading: "7. Payment", paragraphs: ["Payment is made using the methods offered during checkout. The order is considered confirmed only after payment has been effectively validated, subject to any checks that may be required."] },
    { heading: "8. Delivery", paragraphs: ["Products are delivered to the address provided by the customer when ordering. Khaos Theory selects a shipping method suited to the destination, nature and value of the shipment.", "Applicable delivery charges and conditions are presented before the order is validated."] },
    { heading: "9. International deliveries — duties and taxes", paragraphs: ["For deliveries subject to customs formalities, customs duties, import taxes or other local charges may be required by the authorities of the destination country. Unless otherwise stated at the time of ordering, these sums are payable by the recipient and are not included in the amounts invoiced by Khaos Theory."] },
    { heading: "10. Right of withdrawal", paragraphs: ["Where the right of withdrawal applies, the consumer has 14 days from receipt of the goods to exercise that right without giving reasons.", "The fact that a piece of jewellery is made to order does not, by itself, exclude the right of withdrawal.", "Choosing a standard size offered on the website is not considered by Khaos Theory to be product customisation.", "The right of withdrawal may nevertheless be excluded for a product made to the consumer’s specific requirements or clearly personalised, in particular where a specific modification, engraving, special dimensions or a personalised creation has been expressly requested. Where this exception applies, the customer is informed before the order is concluded."] },
    { heading: "11. Exercising the right of withdrawal and returns", paragraphs: ["The customer may notify Khaos Theory of the decision to withdraw by an unambiguous statement sent to contact@khaostheoryparis.com or may use the form in the appendix.", "After notification of withdrawal, the product must be returned within the statutory period to:\nEI – Vincent GÉRARD / Khaos Theory\n231 Rue Saint-Honoré\n75001 Paris\nFrance", "Direct return costs are borne by the customer. The customer must take reasonably necessary precautions to ensure a return appropriate to the nature and value of the jewellery."] },
    { heading: "12. Refund after withdrawal", paragraphs: ["Where the statutory conditions are met, Khaos Theory refunds the sums due in accordance with applicable law and using the same means of payment as used for the initial transaction, unless the customer expressly agrees to another cost-free method.", "The refund may be deferred in cases permitted by law, in particular until the goods have been recovered or until the consumer provides evidence of dispatch."] },
    { heading: "13. Damaged product or delivery issue", paragraphs: ["The customer is invited to contact Khaos Theory promptly at contact@khaostheoryparis.com if a product is received damaged or if there is an error or delivery issue, so that the situation can be handled.", "This step does not limit the consumer’s statutory guarantees and rights."] },
    { heading: "14. Statutory guarantee of conformity", paragraphs: ["The consumer benefits from the statutory guarantee of conformity under the conditions provided by the French Consumer Code. This guarantee applies independently of any commercial guarantee."] },
    { heading: "15. Hidden defects guarantee", paragraphs: ["The customer also benefits from the statutory guarantee for hidden defects under the conditions provided by the French Civil Code."] },
    { heading: "16. Silver, surface treatments, textures and ageing", paragraphs: ["Khaos Theory jewellery is primarily made in silver and may receive various surface treatments, oxidation effects, patinas, textures and finishes.", "These treatments and textures may evolve, fade or change progressively over time and with use. Their evolution may depend in particular on friction, contact with skin, air, humidity, cosmetic or chemical products, and the conditions in which the jewellery is worn and maintained.", "This evolution forms part of the normal ageing and wear of jewellery and may contribute to the development of a patina specific to each piece.", "Evolution resulting from normal use therefore does not, in itself, constitute a defect. This provision does not in any way deprive the consumer of statutory guarantees where a defect covered by those guarantees is actually present."] },
    { heading: "17. Jewellery sizes", paragraphs: ["The customer is responsible for choosing a size from those offered. Choosing the wrong size does not, in itself, constitute a lack of conformity.", "Where technically possible, Khaos Theory may offer resizing on quotation.", "This provision does not limit the exercise of the right of withdrawal where legally applicable."] },
    { heading: "18. Liability", paragraphs: ["Khaos Theory is liable for performing its obligations under the conditions provided by applicable law.", "No provision of these Terms is intended to exclude or limit any mandatory right granted to the consumer."] },
    { heading: "19. Intellectual property", paragraphs: ["The creations, photographs, texts, graphic elements, logos and other content of the Khaos Theory website are protected by applicable intellectual property rights. Any unauthorised reproduction or exploitation is prohibited within the limits provided by law."] },
    { heading: "20. Personal data", paragraphs: ["Personal data necessary to process orders and manage customer relations is processed in accordance with Khaos Theory’s privacy policy, available on the website."] },
    { heading: "21. Customer service", paragraphs: ["For any question relating to an order, delivery, return or refund, Khaos Theory customer service may be contacted at:\ncontact@khaostheoryparis.com"] },
    { heading: "22. Consumer mediation", paragraphs: ["After first submitting a complaint to Khaos Theory and if the dispute remains unresolved, the consumer may refer the matter free of charge to the consumer mediator responsible for Khaos Theory:\nCM2C — Centre de la Médiation de la Consommation de Conciliateurs de Justice\n49 Rue de Ponthieu\n75008 Paris\nFrance\nhttps://www.cm2c.net/"] },
    { heading: "23. Applicable law", paragraphs: ["These Terms are governed by French law, without depriving the consumer of the mandatory protective provisions applicable to them under the relevant legislation."] },
    { heading: "24. Languages", paragraphs: ["These Terms are provided in French and English. The French version is the reference version, without prejudice to the consumer’s mandatory rights."] },
    { heading: "25. Version of the Terms", paragraphs: ["The applicable version is the version accepted by the customer at the time of ordering. Khaos Theory may amend these Terms for future orders."] },
  ],
  withdrawalForm: {
    heading: "APPENDIX — MODEL WITHDRAWAL FORM",
    paragraphs: ["To the attention of:\nEI – Vincent GÉRARD / Khaos Theory\n231 Rue Saint-Honoré\n75001 Paris\nFrance\ncontact@khaostheoryparis.com", "I hereby notify you of my withdrawal from the contract for the sale of the following goods:\nProduct:\nOrder number:\nOrdered on / received on:\nConsumer’s name:\nConsumer’s address:\nDate:\nConsumer’s signature (only if this form is notified on paper):"],
  },
};

export const termsDocuments: Record<Locale, TermsDocument> = { fr, en };
